"""Write the ablation table fragment used by the paper.

Usage: python scripts/export_ablation_tex.py --run results/final/tb2_final --out ../archive/paper_v1/generated_ablation.tex
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any, Dict, List

sys.stdout.reconfigure(encoding="utf-8")

LABEL = {"REP": "repetition", "NOV": "novelty (relevance-blind)", "EVID": "task-grounded evidence",
         "VER": "verification deltas", "WORK": "workspace churn", "SEM": "semantic redundancy"}
DIGIT = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four", "5": "Five",
         "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def spoken(x: str) -> str:
    return "".join(DIGIT.get(c, c) for c in x)


def f(x: Any, nd: int = 3) -> str:
    try:
        v = float(x)
    except (TypeError, ValueError):
        return "--"
    return "--" if v != v else f"{v:.{nd}f}"


def fsgn(x: Any) -> str:
    try:
        v = float(x)
    except (TypeError, ValueError):
        return "--"
    return "--" if v != v else f"{v:+.3f}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    abl = json.load(open(os.path.join(args.run, "ablation.json"), encoding="utf-8"))
    L: List[str] = []
    macros: List[str] = []
    L.append("\\begin{tabular}{lrrr}\\toprule")
    L.append("Channel & alone & without & $\\Delta$ ROC \\\\ \\midrule")
    rows = []
    for ch in abl.get("channels", []):
        alone = abl["per_channel_alone"].get(ch, {})
        loo = abl["leave_one_out"].get(ch, {})
        rows.append((ch, alone.get("roc_auc"), loo.get("roc_auc"), loo.get("delta_roc")))
        L.append(f"{LABEL.get(ch, ch)} & {f(alone.get('roc_auc'))} & {f(loo.get('roc_auc'))} & "
                 f"{fsgn(loo.get('delta_roc'))} \\\\")
        macros.append(f"\\newcommand{{\\pabl{spoken(ch)}AucAlone}}{{{f(alone.get('roc_auc'))}}}")
        macros.append(f"\\newcommand{{\\pabl{spoken(ch)}AucWithout}}{{{f(loo.get('roc_auc'))}}}")
        macros.append(f"\\newcommand{{\\pabl{spoken(ch)}Delta}}{{{fsgn(loo.get('delta_roc'))}}}")
    L.append("\\midrule")
    L.append(f"\\multicolumn{{4}}{{l}}{{all channels: ROC-AUC {f(abl['full'].get('roc_auc'))}, "
             f"PR-AUC {f(abl['full'].get('pr_auc'))}}} \\\\")
    L.append("\\bottomrule\\end{tabular}")
    macros.append(f"\\newcommand{{\\pablFullAuc}}{{{f(abl['full'].get('roc_auc'))}}}")

    out = os.path.abspath(args.out)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("% AUTO-GENERATED by scripts/export_ablation_tex.py -- table fragment\n")
        fh.write("\n".join(L) + "\n")
    macro_path = out.replace("generated_ablation", "ablation_macros")
    with open(macro_path, "w", encoding="utf-8") as fh:
        fh.write("% AUTO-GENERATED ablation macros\n" + "\n".join(macros) + "\n")
    print(f"wrote {out} and {macro_path}")


if __name__ == "__main__":
    main()
