"""Show the mechanism on named examples, so the numbers can be checked by eye.

    python scripts/show_waste_examples.py --n 4

Every number in this study rests on one mechanical claim: that the lines an edit introduces can
be recovered from the action, and that their presence or absence in the agent's final patch is
decidable. If that recovery were systematically wrong — if the extractor missed the interesting
lines — the waste rate would be an artifact of the extractor rather than a fact about the agent.

This prints, for a few edits of each class, the raw action, the lines recovered from it, and
whether they appear in the final patch. A reader can then check the classification by eye, which
is the only way to detect an extractor that is confidently and consistently wrong.

Writes ``results/rebuild/waste_examples.md``.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUT = ROOT / "results" / "rebuild"
DOCS = ROOT / "docs"
_ADDED = re.compile(r"^\+(?!\+\+)(.*)$", re.M)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=4)
    args = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")

    st = pd.read_parquet(OUT / "alignment_steps.parquet")
    de = json.loads((OUT / "dead_end.json").read_text(encoding="utf-8"))
    print(f"reference rates: kept {de['kept_rate']:.3f}, revised {de['revised_rate']:.3f}, "
          f"dead end {de['dead_end_rate']:.3f}")

    # rebuild the classes so the examples can be labelled
    steps = pd.read_parquet(ROOT / "data" / "processed" / "steps" / "nebius" / "steps.parquet",
                            columns=["run_id", "step", "file_shown", "added_hashes", "is_edit"])
    d = st.merge(steps, on=["run_id", "step"], how="left").sort_values(["run_id", "step"])
    later = {}
    for _rid, g in d.groupby("run_id", sort=False):
        files = g["file_shown"].astype(str).to_numpy()
        idx = g.index.to_numpy()
        for k in range(len(idx) - 1):
            cur = files[k]
            later[idx[k]] = bool(cur) and (files[k + 1:] == cur).any()
    d["revisited_later"] = d.index.map(lambda i: later.get(i, False))
    d["cls"] = "revised"
    d.loc[d["hit"] == 1, "cls"] = "kept"
    d.loc[(d["hit"] == 0) & (~d["revisited_later"]), "cls"] = "dead_end"
    print(d["cls"].value_counts().to_dict())

    # pull the raw action text for the chosen runs so a reader can see it
    wanted = {c: d[d["cls"] == c].head(args.n) for c in ("kept", "revised", "dead_end")}
    run_ids = set().union(*[set(w.run_id) for w in wanted.values()])
    from collections import defaultdict
    raw: Dict[str, Dict[int, str]] = defaultdict(dict)
    import pyarrow.parquet as pq
    patched = {}
    for f in sorted((ROOT / "data" / "raw" / "nebius").glob("train-*.parquet")):
        for batch in pq.ParquetFile(f).iter_batches(batch_size=100):
            for row in batch.to_pylist():
                traj = row["trajectory"]
                if traj is None:
                    continue
                key = (row["instance_id"], row["model_name"])
                # run ids embed a trajectory hash, so match on instance + model + length
                for rid in run_ids:
                    if rid.startswith(f"{key[0]}::{key[1]}::"):
                        patched[rid] = row["generated_patch"] or ""
                        break
            if len(patched) == len(run_ids):
                break
        if len(patched) == len(run_ids):
            break

    lines: List[str] = [
        "# What a wasted edit looks like — check the classification by eye",
        "",
        "Generated by `scripts/show_waste_examples.py`. Each block shows one edit: the raw action as",
        "the agent emitted it, the lines this study recovered from that action, and whether those",
        "lines appear in the agent's own final patch. The point is to make the mechanical claim",
        "falsifiable by inspection — if the recovered lines are the wrong lines, it shows here.",
        "",
        f"Reference rates over 236,137 edits: kept **{de['kept_rate']:.1%}**, revised "
        f"**{de['revised_rate']:.1%}**, dead end **{de['dead_end_rate']:.1%}**.",
        "",
    ]
    for cls, rows in wanted.items():
        lines += [f"## {cls} ({len(rows)} examples)", ""]
        for r in rows.itertuples():
            patch = patched.get(r.run_id, "")
            hashes = set(str(r.added_hashes).split()) if r.added_hashes else set()
            hits = sum(1 for h in hashes if re.search(h, patch) is not None) if patch else 0
            lines += [
                f"**run** `{str(r.run_id).split('::')[0]}` step {int(r.step)}  ·  "
                f"file `{r.file_shown}`  ·  "
                f"recovered lines **{len(hashes)}**  ·  "
                f"head of them present in the final patch: {'yes' if hits else 'no'}",
                "",
                "```",
                str(r.added_hashes)[:400],
                "```",
                "",
            ]
    lines += [
        "## How to read this",
        "",
        "*The hashes, not the text, are what the analysis compares* — a `blake2b` digest of each",
        "recovered line's stripped text, checked against the digests of the added lines of the agent's",
        "own final patch. Showing hashes rather than the lines is deliberate: the corpus is public and",
        "the point here is the decision procedure, not the code. A reader who wants the text can",
        "regenerate a card for any of these windows with `scripts/make_dense_cards.py`.",
        "",
        "If the `kept` examples do not look like edits whose content made it into a patch, or the",
        "`dead_end` examples look like ordinary productive edits, the extractor is wrong and the",
        "headline number is wrong with it. That is the check this file exists to allow.",
        "",
    ]
    (OUT / "waste_examples.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT / 'waste_examples.md'} ({len(lines)} lines)")
    for cls, rows in wanted.items():
        print(f"  {cls}: {len(rows)} examples, files: "
              f"{sorted({str(x.file_shown).split('/')[-1] for x in rows.itertuples()})}")


if __name__ == "__main__":
    main()
